import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file was generated by the FlutterFire CLI

// Import the firebase_database package if you plan to use it in main.dart
// import 'package:firebase_database/firebase_database.dart';


// Make the main function asynchronous to initialize Firebase
Future<void> main() async {
  // Ensure that the Flutter binding is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the default options for the current platform
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Run the application
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bus Tracking App',
      theme: ThemeData(
        // Use colorScheme.inversePrimary for the AppBar background for a modern look
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue).copyWith(
          inversePrimary: Colors.blue.shade200, // Adjust shade as needed
        ),
        useMaterial3: true, // Use Material 3 features
      ),
      // Set the home screen to our UserTypeSelectionScreen
      home: const UserTypeSelectionScreen(),
    );
  }
}

// This is our User Type Selection screen widget
class UserTypeSelectionScreen extends StatelessWidget {
  const UserTypeSelectionScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Bus Tracking App'),
        // Use the color from the theme's colorScheme
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: Center( // Center the content vertically and horizontally
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center, // Center column content vertically
          crossAxisAlignment: CrossAxisAlignment.stretch, // Stretch buttons horizontally
          children: <Widget>[
            // Title text
            const Text(
              'Are you a:',
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 24.0,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 40.0), // Add some vertical space

            // Conductor Button
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 40.0), // Add horizontal padding
              child: ElevatedButton(
                onPressed: () {
                  // TODO: Navigate to Conductor Login Screen
                  print('Conductor button pressed'); // Placeholder action
                  // Example Navigation (requires defining the ConductorLoginScreen widget)
                  // Navigator.push(
                  //   context,
                  //   MaterialPageRoute(builder: (context) => const ConductorLoginScreen()),
                  // );
                },
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 15.0), // Button padding
                  textStyle: const TextStyle(fontSize: 18), // Button text size
                  shape: RoundedRectangleBorder( // Rounded corners
                    borderRadius: BorderRadius.circular(10.0),
                  ),
                ),
                child: const Text('Bus Conductor'),
              ),
            ),
            const SizedBox(height: 20.0), // Add vertical space between buttons

            // Passenger Button
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 40.0), // Add horizontal padding
              child: ElevatedButton(
                onPressed: () {
                  // TODO: Navigate to Passenger Destination Selection Screen
                  print('Passenger button pressed'); // Placeholder action
                  // Example Navigation (requires defining the PassengerDestinationScreen widget)
                  // Navigator.push(
                  //   context,
                  //   MaterialPageRoute(builder: (context) => const PassengerDestinationScreen()),
                  // );
                },
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 15.0), // Button padding
                  textStyle: const TextStyle(fontSize: 18), // Button text size
                  shape: RoundedRectangleBorder( // Rounded corners
                    borderRadius: BorderRadius.circular(10.0),
                  ),
                ),
                child: const Text('Passenger'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// TODO: Define your ConductorLoginScreen and PassengerDestinationScreen widgets
// Example placeholder:
// class ConductorLoginScreen extends StatelessWidget {
//   const ConductorLoginScreen({Key? key}) : super(key: key);
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(title: const Text('Conductor Login')),
//       body: const Center(child: Text('Conductor Login Screen')),
//     );
//   }
// }

// Example placeholder:
// class PassengerDestinationScreen extends StatelessWidget {
//   const PassengerDestinationScreen({Key? key}) : super(key: key);
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(title: const Text('Select Destination')),
//       body: const Center(child: Text('Passenger Destination Selection Screen')),
//     );
//   }
// }
